# Generated by Django 3.1 on 2020-08-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain_Name', models.CharField(max_length=100, unique=True)),
                ('Client_Ip4', models.CharField(max_length=16)),
                ('Domain_Secret', models.CharField(max_length=50)),
                ('Last_Change', models.DateTimeField(blank=True, null=True)),
                ('Client_Type', models.CharField(blank=True, max_length=500, null=True)),
                ('Client_LAN', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
