# Generated by Django 3.1 on 2020-08-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddns_updater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='Domain_Secret',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
