# Generated by Django 3.1 on 2020-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddns_updater', '0002_auto_20200806_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='RECORD_TYPE',
            field=models.CharField(choices=[('A', 'A'), ('TXT', 'TXT'), ('CNAME', 'CNAME')], default='1', max_length=10),
        ),
    ]
