# Generated by Django 3.1 on 2020-08-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddns_updater', '0003_domain_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='RECORD_TYPE',
            field=models.CharField(choices=[('A', 'A'), ('TXT', 'TXT'), ('CNAME', 'CNAME')], default='A', max_length=10),
        ),
    ]
