# Generated by Django 3.1 on 2020-08-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddns_updater', '0004_auto_20200810_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='TTL_VALUE',
            field=models.IntegerField(default=60),
        ),
    ]
