# Generated by Django 3.1 on 2020-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddns_updater', '0005_domain_ttl_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='RECORD_TYPE',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('TXT', 'TXT'), ('CNAME', 'CNAME')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='domain',
            name='TTL_VALUE',
            field=models.IntegerField(blank=True, default=60),
        ),
    ]
